[package]
name = "gps-rust"
version = "0.1.0"
authors = ["ckfy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adafruit_gps = { path = "adafruit_gps" }
gpx = "0.8.1"
chrono = "0.4"
geo-types = "0.4.3"

[[bin]]
name = "main"
path = "src/main.rs"